Repository Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System, pull requests merged in 2022-12, with the labels that each got.

#13 Features
  Login System Architecture/Final Page Navigation.py
  Login System Architecture/Login Form Database.py
  Login System Architecture/Login Form.py
  Login System Architecture/Login.png
  Login System Architecture/README.md
  Login System Architecture/Sign Up.png
  Login System Architecture/dataset.txt
Labels: enhancement, amazing

#18 Changed Date Entry to Calender
  Final.py
Labels: enhancement, amazing, KWOC

#20 Update ContributorsList.js
  ContributorsList.js
Labels: good first issue

#17 Updating Final.py :: reviewing possible Security issues (SQL string injection) and custom Refactoring && Updating ContributorsList.js
  ContributorsList.js
  Final.py
Labels: enhancement, KWOC

#33 updated calendar entry format
  Final.py
Labels: enhancement

#37 improvement in lock_screen.py
  lock_screen.py
Labels: enhancement
