Repository Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System, pull requests merged in 2023-06, with the labels that each got.

#159 Added the logo related to issue-156
  README.md
  bus-booking-system/Image/logo.png
Labels: enhancement, gssoc23, level1

#160 Added Pull Request Template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: gssoc23, level1

#169 Added Show Password Feature.
  bus-booking-system/Modules/SignIn_Module/SignIn_page.py
Labels: gssoc23

#173 Added Alert Box after Successful User Registration.
  bus-booking-system/Modules/SignIn_Module/SignIn_page.py
Labels: gssoc23, level1

#170 Create auto-comment.yml
  .github/workflows/auto-comment.yml
Labels: gssoc23, level3

#177 Password checker during registration
  .DS_Store
  bus-booking-system/.DS_Store
  bus-booking-system/Modules/SignIn_Module/SignIn_page.py
Labels: gssoc23, level2

#179 update documentation issue template
  .github/ISSUE_TEMPLATE/Documentation.yml
Labels: gssoc23, level1

#178 Fixed the Aspect Ratio Bug on Add Bus Window
  bus-booking-system/BufferData/CurrentUser/password.txt
  bus-booking-system/BufferData/CurrentUser/username.txt
  bus-booking-system/Modules/SignIn_Database/password.txt
  bus-booking-system/Modules/SignIn_Database/username.txt
  bus-booking-system/My_database
  bus-booking-system/main.py
Labels: gssoc23, level1

#183 [DONE] Documentation update in code
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  ContributorsList.js
  README.md
Labels: gssoc23, level1

#182 Integrated SQLite3 database and validation also removed login bugs
  BufferData\CurrentUser\password.txt
  BufferData\CurrentUser\username.txt
  bus-booking-system/Modules/SignIn_Module/SignIn_page.py
  user_credentials.db
Labels: gssoc23, level2

#186 Added forget password using sqlite3 database and removed bugs while updating password.
  My_database
  bus-booking-system/Modules/SignIn_Module/SignIn_page.py
  user_credentials.db
Labels: gssoc23, level2

#190 Resolved cloning-related bugs/errors
  BufferData\CurrentUser\password.txt
  Modules\SignIn_Module\SignIn_Check.txt
  bus-booking-system/BufferData/CurrentUser/username.txt
  bus-booking-system/Modules/SignIn_Module/SignIn_page.py
  user_credentials.db
Labels: gssoc23, level1

#201 feat: add codeql workflow
  .github/workflows/codeql.yml
Labels: gssoc23, level1
